SELECT TOP (1000) [Flight_Number]
      ,[Launch_Date]
      ,[Launch_Time]
      ,[Launch_Site]
      ,[Vehicle_Type]
      ,[Payload_Name]
      ,[Payload_Type]
      ,[Payload_Mass_kg]
      ,[Payload_Orbit]
      ,[Customer_Name]
      ,[Customer_Type]
      ,[Customer_Country]
      ,[Mission_Outcome]
      ,[Failure_Reason]
      ,[Landing_Type]
      ,[Landing_Outcome]
  FROM Space.dbo.lanzamientos
